#ifndef RAM_REGS
# define RAM_REGS \
{RDWR, NULL}, \
{RDWR, NULL}, \
{RDWR, NULL}, \
{PROHIB, NULL}, \
{RDWR, &Memory_controller::write_div}, \
{RDWR, NULL}, \
{RDWR, NULL}, \
{RDWR, &Memory_controller::write_tac}, \
{PROHIB, NULL}, \
{PROHIB, NULL}, \
{PROHIB, NULL}, \
{PROHIB, NULL}, \
{PROHIB, NULL}, \
{PROHIB, NULL}, \
{PROHIB, NULL}, \
{RDWR, NULL}, \
{RDWR, NULL}, \
{RDWR, NULL}, \
{RDWR, NULL}, \
{WR, NULL}, \
{RDWR, NULL}, \
{PROHIB, NULL}, \
{RDWR, NULL}, \
{RDWR, NULL}, \
{WR, NULL}, \
{RDWR, NULL}, \
{RDWR, NULL}, \
{RDWR, NULL}, \
{RDWR, NULL}, \
{WR, NULL}, \
{RDWR, NULL}, \
{PROHIB, NULL}, \
{RDWR, NULL}, \
{RDWR, NULL}, \
{WR, NULL}, \
{RDWR, NULL}, \
{RDWR, NULL}, \
{RDWR, NULL}, \
{RDWR, NULL}, \
{PROHIB, NULL}, \
{PROHIB, NULL}, \
{PROHIB, NULL}, \
{PROHIB, NULL}, \
{PROHIB, NULL}, \
{PROHIB, NULL}, \
{PROHIB, NULL}, \
{PROHIB, NULL}, \
{PROHIB, NULL}, \
{PROHIB, NULL}, \
{PROHIB, NULL}, \
{PROHIB, NULL}, \
{PROHIB, NULL}, \
{PROHIB, NULL}, \
{PROHIB, NULL}, \
{PROHIB, NULL}, \
{PROHIB, NULL}, \
{PROHIB, NULL}, \
{PROHIB, NULL}, \
{PROHIB, NULL}, \
{PROHIB, NULL}, \
{PROHIB, NULL}, \
{PROHIB, NULL}, \
{PROHIB, NULL}, \
{PROHIB, NULL}, \
{RDWR, &Memory_controller::write_lcdc}, \
{RDWR, &Memory_controller::write_stat}, \
{RDWR, &Memory_controller::write_scy}, \
{RDWR, &Memory_controller::write_scx}, \
{RD, &Memory_controller::write_ly}, \
{RDWR, &Memory_controller::write_lyc}, \
{WR, &Memory_controller::write_dma}, \
{WR, NULL}, \
{WR, NULL}, \
{WR, NULL}, \
{RDWR, NULL}, \
{RDWR, NULL}, \
{PROHIB, NULL}, \
{RDWR, NULL}, \
{PROHIB, NULL}, \
{RDWR, NULL}, \
{PROHIB, NULL}, \
{WR, NULL}, \
{WR, NULL}, \
{WR, NULL}, \
{WR, NULL}, \
{WR, &Memory_controller::write_hdma5}, \
{RDWR, NULL}, \
{PROHIB, NULL}, \
{PROHIB, NULL}, \
{PROHIB, NULL}, \
{PROHIB, NULL}, \
{PROHIB, NULL}, \
{PROHIB, NULL}, \
{PROHIB, NULL}, \
{PROHIB, NULL}, \
{PROHIB, NULL}, \
{PROHIB, NULL}, \
{PROHIB, NULL}, \
{PROHIB, NULL}, \
{PROHIB, NULL}, \
{PROHIB, NULL}, \
{PROHIB, NULL}, \
{PROHIB, NULL}, \
{PROHIB, NULL}, \
{RDWR, NULL}, \
{RDWR, &Memory_controller::write_bcpd}, \
{RDWR, NULL}, \
{RDWR, &Memory_controller::write_ocpd}, \
{PROHIB, NULL}, \
{PROHIB, NULL}, \
{PROHIB, NULL}, \
{PROHIB, NULL}, \
{RDWR, &Memory_controller::write_svbk}, \
{PROHIB, NULL}, \
{PROHIB, NULL}, \
{PROHIB, NULL}, \
{PROHIB, NULL}, \
{PROHIB, NULL}, \
{PROHIB, NULL}, \
{PROHIB, NULL}, \
{PROHIB, NULL}, \
{PROHIB, NULL}, \
{PROHIB, NULL}, \
{PROHIB, NULL}, \
{PROHIB, NULL}, \
{PROHIB, NULL}, \
{PROHIB, NULL}, \
{PROHIB, NULL}
#endif
